### ISSUE TITLE
est 全局插件安装后编译含有grid下mixin时报错

### ISSUE THREAD

**Issue by Phinome** [ecomfe/est#32]
问题R;T：

E.g：

layout.less
```less

.main {
    .make-column(2/3, 5%);
}

```
`lessc layout.less --est --autoprefix throw NameError: .make-column is undefined in layout.less`

est , autoprefix 都是以插件形式安装在全局的，即： `npm install -g less-plugin-est less-plugin-autoprefix`

环境说明：

`lessc 2.5.0 (Less Compiler) [JavaScript]`
`node version v0.12.2`
`npm version 2.7.5`

最新说明：查看了`src/all.less`中没有 `@import 'grid.less'`，`vim src/all.less` 修复此问题，也烦请你修改一下吧。😁

**Comment by Justineo** [comment]
Fixed in v2.0.1.
