### ISSUE TITLE
.margin-rem的问题（.padding-rem同样存在）

### ISSUE THREAD

**Issue by EarlyBirdMe** [ecomfe/est#34]
.margin-rem(10 0);

编译后输出：===》

.margin:10 10;

我觉得应该是.
.margin:10 0;吧

看了下源码：
.margin-rem(@px-size) {
    @margin-top: ~`Number('@{px-size}'.match(/(\d+|\d*\.\d+)+/g)[0])`;
    @margin-right: ~`Number('@{px-size}'.match(/(\d+|\d*\.\d+)+/g)[1]) || @{margin-top}`;
    @margin-bottom: ~`Number('@{px-size}'.match(/(\d+|\d*\.\d+)+/g)[2]) || @{margin-top}`;
    @margin-left: ~`Number('@{px-size}'.match(/(\d+|\d*\.\d+)+/g)[3]) || @{margin-right} || @{margin-top}`;
    @top-rem-size: @margin-top / @default-font-size;
    margin-top: ~"@{margin-top}px";
    margin-top: ~"@{top-rem-size}rem";

    @right-rem-size: @margin-right / @default-font-size;
    margin-right: ~"@{margin-right}px";
    margin-right: ~"@{right-rem-size}rem";

    @bottom-rem-size: @margin-bottom / @default-font-size;
    margin-bottom: ~"@{margin-bottom}px";
    margin-bottom: ~"@{bottom-rem-size}rem";

    @left-rem-size: @margin-left / @default-font-size;
    margin-left: ~"@{margin-left}px";
    margin-left: ~"@{left-rem-size}rem";
}

是因为把空值和0值，统一当成了false判断了，不知是有意为之还是bug，不过使用起来不太方便
需要.margin:10 0;的情况，我都得拆出来写，不太科学，望采纳

**Comment by Justineo** [comment]
是一个 bug，修复了并且优化了输出。bug fix 会在下个版本发布。

**Comment by EarlyBirdMe** [comment]
.padding-em与margin-em也统一改下哈，谢谢啦

**Comment by EarlyBirdMe** [comment]
看到你的fix了，太巧妙了，学习了！

**Comment by leeight** [comment]
不明觉厉

**Comment by zmmbreeze** [comment]
不明觉厉
