### ISSUE TITLE
clockhand 这个里面的内容能否归在 util 里呢？

### ISSUE THREAD

**Issue by Phinome** [ecomfe/est#38]
R；T
个人认为 clockhand 这个分类有些模糊，为啥不放入 util ，想知道一下你的想法。😀

**Comment by Justineo** [comment]
[rider](https://github.com/ecomfe/rider/tree/master/lib/rider) 里面是这么分的，est 就搬过来了。`clockhand` 功能还算独立吧，放一个模块我觉得问题不太大。现在基本是不知道放哪的放在 `util` 里。

**Comment by Phinome** [comment]
之前一直不太明白 `clockhand` 这个为啥要单独存在，难道有使用者是逆向写的？ 😀
就这样吧，我明白你的意思了。

**Comment by Justineo** [comment]
不是的，只是给上右下左的属性增加个快捷写法。比如我要上边框和左边框的颜色，只要写

```less
.border-color(red, _, _, blue);
```

就可以生成：

```css
border-top-color: red;
border-left-color: blue;
```

 我刚顺便优化了一下这个模块的输出，后面可以优先合并属性了，比如：

```less
.border-color(red, red, red, red);
```

现在会输出合并后的

```css
border-color: red
```

而不是四个方向分开的值了。

**Comment by Phinome** [comment]
嗯，这下完全明白你的意思了，你这样一说，`clockhand` 这个分类的确很对～

**Comment by Justineo** [comment]
那没问题了我关了。
