### ISSUE TITLE
@default-base-font-family 的值为何只有"Helvetica Neue", Arial, sans-serif?

### ISSUE THREAD

**Issue by helloyxw** [ecomfe/est#46]
中文字体都采用sans-serif 处理吗？ 合理性在哪里？

**Comment by Justineo** [comment]
合理性在于会 fallback 到浏览器默认的中文字体。

**Comment by helloyxw** [comment]
但是系统默认的中文字体好看吗？在美观上是怎么考虑的呢？

**Comment by Justineo** [comment]
这是设计样式的人考虑的问题，默认配置不会做太多设置。est 是一个让你方便编写样式代码的库，究竟样式如何设计好看，不会关注太多。而且配置也就一行的事，自己按需求去配就好了。
