### ISSUE TITLE
支持在创建插件的时候指定全局变量

### ISSUE THREAD

**Issue by otakustay** [ecomfe/est#50]
对于在[变量](http://ecomfe.github.io/est/#variables)章节中列出的内容，希望都可以在`new Est()`的时候通过JavaScript传递，这样就不需要再单独维护一个控制的`.less`文件并在各处均要引用了

另外 `@support-ie-version`的值为多少可以完全无视IE？

**Comment by Justineo** [comment]
你是在 webpack 项目里用吗？可以试试 [style-resources-loader](https://www.npmjs.com/package/style-resources-loader)？

> 另外 @support-ie-version的值为多少可以完全无视IE？

按代码里处理的逻辑，`10` 就行了。

**Comment by otakustay** [comment]
已用`style-resources-loader`搞定
